import Head from 'next/head'
import Hero from '../Components/Hero'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Photography Next</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

    <Hero heading='Captur Photography' message='I capture moments in nature and keep them alive'/>
    </div>
  )
}
